In [12]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


In [4]:
#one Dimension Array
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
#Two Dimension Array
b=np.array([[1,2],[2,4]])
print(b)

[[1 2]
 [2 4]]


In [8]:
#Three Dimension Array
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [9]:
#Access the element using index
a=np.array([1,2,3,4])
print(a[0])
print(a[-1])

1
4


In [13]:
#Arange Function
arange=np.arange(0,10,2)
print(arange)
range2=np.arange(2,20,3)
print(range2)

[0 2 4 6 8]
[ 2  5  8 11 14 17]


In [14]:
#Linespace function
linespace=np.linspace(0,1,5)
print(linespace)

[0.   0.25 0.5  0.75 1.  ]


In [16]:
#Reshape function
a=arange=np.arange(0,12)
print(a)
b=np.reshape(a, (4, 3))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
#Matrix addition
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [10, 11, 12]])
C = A + B
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Sum of matrices:\n", C)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[ 7  8  9]
 [10 11 12]]
Sum of matrices:
 [[ 8 10 12]
 [14 16 18]]
